### ISSUE TITLE
Outdated folder + help wanted

### ISSUE THREAD

**Issue by marktani** [graphcool/templates#103]

**Comment by heymartinadams** [comment]
Hi @marktani, just because these functions have been moved into an `outdated` folder doesn’t mean they’re no longer usable, correct?

Do you need help updating them?

**Comment by marktani** [comment]
Hey @heymartinadams :wave:
Examples in the outdated folder are not using the latest function runtime yet. Furthermore, not all examples there qualify as full-blown templates (for example the different Stripe examples).

Help with updating them is more than welcome, ping me in Slack beforehand to get on the same page 🙂
