### ISSUE TITLE
Auth0 authentication template

### ISSUE THREAD

**Issue by marktani** [graphcool/templates#108]
See https://github.com/graphcool/templates/tree/master/outdated/auth/auth0-authentication for an outdated version.

I'd be happy to help you getting started if you want to contribute an Auth0 template, please contact me in [Slack](https://slack.graph.cool) 🙂

**Comment by marktani** [comment]
This is WIP: https://github.com/graphcool/templates/pull/112

**Comment by wdoug** [comment]
I think this could be closed now since #112 was merged.
