### ISSUE TITLE
Google auth mutation is not working

### ISSUE THREAD

**Issue by jurosh** [graphcool/templates#116]
### Issue type:

I am submitting:

- [x] an issue

#### What OS and OS version are you experiencing the issue(s) on?

Deployed from windows. (graphcool/0.8.5 (windows-x64) node-v7.6.)

#### What is the expected behavior?

Function should return token.

#### What is the actual behavior?

Function returning error (in logs) for googleAuthentication:

```
{"error":"Function returned invalid status code: 0. Raw body: empty.last"}
```

#### What steps may we take to reproduce the behavior?

Install `graphcool add-template graphcool/templates/auth/google`, deploy and use in GraphQL console with google token.

```
mutation {
	authenticateGoogleUser(googleToken:
"correct_token...") {
    token
  }  
}
```

I got feeling that it's some issue with using async/await, cause similar, or same issue I've got with example hello world (TypeScript) example deployed to graphcool service

**Comment by jurosh** [comment]
Ouc, looks like after applying auth template, now none of custom functions is working...

event simple like this

```
export default event => {
  return {
    data: {
      message: 'test'
    }
  };
};
```

You can try `https://api.graph.cool/simple/v1/cj9bkf0ka477e01325q9h7rf2`

```
{
	hello {
    message
  }
}
```

Error message doesn't contain anything what might help:
![Image](https://screen.jurosh.com/i16/2017_10_29_59_2533728244620714582.png)

**Comment by kbrandwijk** [comment]
These errors are unrelated to this template.
https://github.com/graphcool/framework/issues/1031
https://github.com/graphcool/framework/issues/1073

**Comment by jurosh** [comment]
Thanks @kbrandwijk 
Will subscribe to both topics.

Strange was that issue started after I added google auth, but definitely it looks like it will be strongly related to that framework issues.

Closing.
