### ISSUE TITLE
Email-password authentication returning an unhandled error

### ISSUE THREAD

**Issue by ZaninAndrea** [graphcool/templates#128]
Hi,
I followed the instructions [here](https://github.com/graphcool/templates/tree/master/auth/email-password) to install the email-password template.

Running the example mutation
```graphql
mutation {
  signupUser(email: "99.zanin@gmail.com", password: "__PASSWORD__") {
    token
  }
}
```

The following error arises
```json
{
  "data": {
    "signupUser": null
  },
  "errors": [
    {
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "signupUser"
      ],
      "code": 5000,
      "message": "A function returned an unhandled error. Please check the logs for executionId 'eu-west-1:simple:cj9tyz5jl08nt0175m45favux'",
      "requestId": "eu-west-1:simple:cj9tyz5jl08nt0175m45favux"
    }
  ]
}
```

**Comment by benjaminogles** [comment]
I had to remove a bunch of ES6 syntax features to get it to work. I don't know if the templates assume that we have a webpack config to transpile everything before deploying or if I am missing something else.

**Comment by ZaninAndrea** [comment]
Issue solved: I was deploying from windows, switching to Ubuntu made the trick
