### ISSUE TITLE
Auth0 authentication broken on React Native

### ISSUE THREAD

**Issue by ylac** [graphcool/templates#131]
### Issue type:

I am submitting:

- [ X ] an issue

#### What OS and OS version are you experiencing the issue(s) on?
graphcool@0.9.2, react-native-auth0@1.2.1, react-native@0.44.3.

#### What is the actual behavior?

Authentication fails with app-side error: "[Error: GraphQL error: function execution error: An unexpected error occured]".

In graphcool function log we can see: 

> {"event":"{\"data\":{\"accessToken\":\"[redacted]"},\"context\":{\"request\":{\"sourceIp\":\"54.199.218.174\",\"headers\":{},\"httpMethod\":\"post\"},\"auth\":null,\"sessionCache\":{},\"environment\":{},\"graphcool\":{\"rootToken\":\"[redacted]",\"endpoints\":{\"simple\":\"https://api.graph.cool/simple/v1/cj9q9rwxnc7z80136mm3gr6wq\",\"relay\":\"https://api.graph.cool/relay/v1/cj9q9rwxnc7z80136mm3gr6wq\",\"system\":\"https://api.graph.cool/system\",\"subscriptions\":\"wss://subscriptions.us-west-2.graph.cool/v1/cj9q9rwxnc7z80136mm3gr6wq\"},\"projectId\":\"cj9q9rwxnc7z80136mm3gr6wq\",\"alias\":null,\"pat\":\"[redacted]",\"serviceId\":\"cj9q9rwxnc7z80136mm3gr6wq\"}}}","logs":[{"2017-11-13T03:41:39.682Z":"Error: Unable to retrieve key identifier from token\n    at /var/task/src/auth0/auth0Authentication.js:49:19\n    at verifyToken (/var/task/src/auth0/auth0Authentication.js:45:12)\n    at Object.<anonymous> (/var/task/src/auth0/auth0Authentication.js:104:38)\n    at step (/var/task/src/auth0/auth0Authentication.js:32:23)\n    at Object.next (/var/task/src/auth0/auth0Authentication.js:13:53)\n    at /var/task/src/auth0/auth0Authentication.js:7:71\n    at __awaiter (/var/task/src/auth0/auth0Authentication.js:3:12)\n    at exports.default (/var/task/src/auth0/auth0Authentication.js:94:45)\n    at executeFunction (/var/task/src/auth0/auth0Authentication-lambda.js:12:19)\n    at exports.handle (/var/task/src/auth0/auth0Authentication-lambda.js:7:3)"}],"returnValue":{"error":"An unexpected error occured"}}

#### What steps may we take to reproduce the behavior?

Setup react-native-auth0 as per: https://github.com/auth0/react-native-auth0, using webAuth. 

Follow steps in: https://github.com/graphcool/templates/tree/master/auth/auth0. Then change auth0 client type to "Native" and enable the "Authorization Code" grant type. 

Then try sign-up/login using Facebook/Google/email. Error is same for each case.

**Comment by ylac** [comment]
Fixed by adding audience: 'http://localhost:8080/', responseType: 'token' to auth0.authorize as per #121

**Comment by kdipaolo** [comment]
@ylac I'm experiencing this same issue, could you elaborate on how you fixed it?
