### ISSUE TITLE
Utility functions in a template - Please vote

### ISSUE THREAD

**Issue by iamclaytonray** [graphcool/templates#134]
Currently, utility functions are not supported very well in the current templates. I'm proposing (and will implement in a PR if I receive enough upvotes), a bunch of functions for common tasks.

- [ ] Password hashing/salting/encryption
- [ ] Email verification (checks to see if the email is valid; if not, reformats the email)
- [ ] Slug verification (similar as above)
- [ ] Phone number verification (similar as above)

That's enough to get started with, for now. I'd love to hear other **general** utility functions that you see a use-case for.

**Please only vote on this issue. Do not spam with a million comments. To make it easier, I have voted with a thumbs up and a thumbs down. Please keep comments to other features and questions so that we can be more productive.**

Also, happy Thanksgiving everyone!

**Comment by kbrandwijk** [comment]
Somewhat related: https://github.com/graphcool/framework/issues/736. These functions could live in a separate package for easy re-use.

**Comment by iamclaytonray** [comment]
I think the benefit in throwing them into a template would be to add hooks into functions that are controlled. What are your thoughts? My initial thoughts on throwing them onto NPM would be lack of control and less extension for individual functions.

**Comment by iamclaytonray** [comment]
Closing for now.
